# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# custom plugins
plugins:          ./_plugins

# Setup
title:            Sumith
tagline:          ': Optimized Awesomeness'
description:      'Programmer · Book Addict · Foodie'
message:          'Continuous and focused efforts bring happiness'
url:              http://sumith1896.github.io/
paginate:         1

author:
  name:           'Sumith'
  email:          sumith1896@gmail.com

# source of the 'modified-lanyon' theme
github:
  main:           https://github.com/Sumith1896

# contact details
contact:
  github:         https://github.com/Sumith1896
  facebook:       https://www.facebook.com/sumith.iitb
  gmail:          mailto:sumith1896@gmail.com

source:      .
destination: ./_site

timezone: Asia/Mumbai

devurl: http://sumith1896.github.io/
port: 4000
host: 0.0.0.0
baseurl: /
